# Generated by Django 3.2.9 on 2021-11-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_auto_20211104_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_model',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
