# Generated by Django 3.2.9 on 2021-11-09 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_alter_message_model_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message_model',
            old_name='exact_time',
            new_name='time',
        ),
    ]
