# Generated by Django 3.2.9 on 2021-11-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_rename_exact_time_message_model_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
            ],
        ),
    ]
